.catalog:
  name: Demo
  description: |
    (Training) Catalog Demo
  version: 0.2
  minimum_rancher_version: v1.0.0
  maintainer: "Rancher-CN <rancher-cn@outlook.com>"
  questions:
    - variable: "scale_number"
      description: |
        Scale Number 
      label: "Webapp Scale Number:"
      default: "1"
      required: true
      type: "int"
    - variable: "ext_port"
      description: |
        External Port
      label: "LoadBalancer External Port:"
      default: "8080"
      required: true
      type: "int"

version: '2'
services:
  webapp:
    scale: $scale_number
    start_on_create: true
  loadbalancer:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ''
        priority: 1
        protocol: http
        service: webapp
        source_port: $ext_port
        target_port: 8080
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      interval: 2000
